# Generated by Django 3.2 on 2021-05-03 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('set_of_likes', models.ManyToManyField(related_name='users_who_liked_this', to=settings.AUTH_USER_MODEL)),
                ('set_of_people', models.ManyToManyField(related_name='people_who_comprise_df', to='fake.People')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='posts_with_person',
            field=models.ManyToManyField(related_name='posts_with_person', to='fake.Post'),
        ),
    ]
