# Generated by Django 3.2 on 2021-05-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='output_df',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
